### ISSUE TITLE
Installing johnny-five, galileo-io

### ISSUE THREAD

**Issue by freshfruit** [rwaldron/galileo-io#42]
I installed the  johnny-five, galileo-io modules on the iot dev kit image v 1.5. I am using a Galileo 1l
. when I try to run the following example "index.js"
```javascript
var five = require("johnny-five");
var Galileo = require("galileo");
var board = five.Board({
  io: new Galileo()
});

board.on("ready", function() {
  new five.Led(13).blink(500);
});
````
as follows`:
` node index.js`
 
I get this error:

```javascript
module.js:340
    throw err;
          ^
Error: Cannot find module 'galileo'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/root/index.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Any help how to resolve this please? I am new to Node development. Thanks

**Comment by fivdi** [comment]
Try with `require("galileo-io")` rather than `require("galileo")`
